config/routes.rb
Fiensview::Application.routes.draw do
  resources :fines do
    post 'search', to: 'fines#search', on: :collection, as: :search
    get 'search', to: 'fines#search_form', on: :collection, as: :search_form
  end

  root 'fines#index'

  

end

app/models/fine.rb
class Fine < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fines_controller.rb
class FinesController < ApplicationController
  require 'active_support/core_ext/date/calculations'

  before_action :set_fine, only: [:show, :edit, :update, :destroy]

  # GET /fines
  # GET /fines.json
  def index
    @fines = Fine.all
  end

  # GET /fines/1
  # GET /fines/1.json
  def show
  end

  # GET /fines/new
  def new
    @fine = Fine.new
  end

  # GET /fines/1/edit
  def edit
  end

  # POST /fines
  # POST /fines.json
  def create
    @fine = Fine.new(fine_params)

    respond_to do |format|
      if @fine.save
        format.html { redirect_to @fine, notice: 'Fine was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fine }
      else
        format.html { render action: 'new' }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fines/1
  # PATCH/PUT /fines/1.json
  def update
    respond_to do |format|
      if @fine.update(fine_params)
        format.html { redirect_to @fine, notice: 'Fine was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fines/1
  # DELETE /fines/1.json
  def destroy
    @fine.destroy
    respond_to do |format|
      format.html { redirect_to fines_url }
      format.json { head :no_content }
    end
  end

  # POST /fines/search
  def search
    params = Hash[search_parameters.map { |k,v| [k, k=='taken_at' ? [Date.parse(v)..Date.parse(v)+1.day] : v] }]

    @fines = Fine.where(params)
  end

  # GET /fines/search_form
  def search_form
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fine
      @fine = Fine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fine_params
      params.require(:fine).permit(:number, :plate, :taken_at, :amount)
    end

  def search_parameters
    params.permit(:number, :plate, :taken_at).select { |k,v| !v.blank? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fines_helper.rb
module FinesHelper
end

app/views/fines/_fine.html.erb
<tr>
  <td><%= fine.number %></td>
  <td><%= fine.plate %></td>
  <td><%= fine.taken_at %></td>
  <td><%= fine.amount %></td>
  <td><%= link_to 'Show', fine %></td>
  <td><%= link_to 'Edit', edit_fine_path(fine) %></td>
  <td><%= link_to 'Destroy', fine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/fines/_form.html.erb
<%= form_for(@fine) do |f| %>
  <% if @fine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fine.errors.count, "error") %> prohibited this fine from being saved:</h2>

      <ul>
      <% @fine.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :plate %><br>
    <%= f.text_field :plate %>
  </div>
  <div class="field">
    <%= f.label :taken_at %><br>
    <%= f.datetime_select :taken_at %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fines/_list.html.erb
<table>
  <thead>
  <tr>
    <th>Number</th>
    <th>Plate</th>
    <th>Taken at</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
    <%= render @fines %>
  </tbody>
</table>

app/views/fines/edit.html.erb
<h1>Editing fine</h1>

<%= render 'form' %>

<%= link_to 'Show', @fine %> |
<%= link_to 'Back', fines_path %>

app/views/fines/index.html.erb
<h1>Listing fines</h1>

<%= render 'list' %>

<br>

<%= link_to 'New Fine', new_fine_path %>
<br/>
<%= link_to 'Search', search_fines_path %>

app/views/fines/new.html.erb
<h1>New fine</h1>

<%= render 'form' %>

<%= link_to 'Back', fines_path %>

app/views/fines/search.html.erb
<h1>Search results</h1>

<%= render 'list' %>

<%= link_to 'Back', fines_path %>

app/views/fines/search_form.html.erb
<h1>Search fines</h1>

<%= form_tag do %>
    <%= label_tag(:number, 'Numero:') %>
    <%= text_field_tag(:number) %>
    <br/>

    <%= label_tag(:plate, 'Targa:') %>
    <%= text_field_tag(:plate) %>
    <br/>

    <%= label_tag(:taken_at, 'Data:') %>
    <%= date_field_tag(:taken_at) %>
    <br/>

    <%= submit_tag('Cerca') %>
<% end %>

app/views/fines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @fine.number %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @fine.plate %>
</p>

<p>
  <strong>Taken at:</strong>
  <%= @fine.taken_at %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @fine.amount %>
</p>

<%= link_to 'Edit', edit_fine_path(@fine) %> |
<%= link_to 'Back', fines_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fiensview</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>Customer: <%= FINESVIEW_CONFIG['customer'] %></footer>

</body>
</html>